#include "globals.hpp"

int SCALED_SCREEN_W = SCREEN_W * GRAPHICS_SCALE;
int SCALED_SCREEN_H = SCREEN_H * GRAPHICS_SCALE;

SDL_Window* WINDOW;
SDL_Renderer* RENDERER;
SDL_Texture* SPRITE_TEXTURE;
SDL_Texture* SCENERY_TEXTURE;
