#include "globals.hpp"

int SCALED_SCREEN_W = SCREEN_W * GRAPHICS_SCALE;
int SCALED_SCREEN_H = SCREEN_H * GRAPHICS_SCALE;

SDL_Window* WINDOW;
SDL_Renderer* RENDERER;

SDL_Texture* BG_TEXTURE = NULL;
SDL_Texture* SPRITE_TEXTURE = NULL;

SDL_Rect* COLLISION_MASK_RECTS = NULL;
SDL_Rect* SPRITE_RECTS = NULL;

Animation* ANIMATIONS = NULL;

CollisionMask** COLLISION_MASKS = NULL;
